export const API_ENDPOINTS = {
  QUERY: '/api/query',
  ENHANCE: '/api/enhance',
  UPLOAD_SESSION: '/api/upload-session',
  CHAT_SESSION: '/api/chat-session',
};

export const ERROR_CODES = {
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  INVALID_JSON: "INVALID_JSON",
  EMPTY_PROMPT: "EMPTY_PROMPT",
  AI_GENERATION_FAILED: "AI_GENERATION_FAILED",
  EMPTY_SQL: "EMPTY_SQL",
  DANGEROUS_INTENT: "DANGEROUS_INTENT",
  QUERY_EXECUTION_FAILED: "QUERY_EXECUTION_FAILED",
  INVALID_RESPONSE: "INVALID_RESPONSE",
  CHAT_RESPONSE: "CHAT_RESPONSE",
  AI_REFUSAL: "AI_REFUSAL",
};
